
POST http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "id":"abcdef",
    "price": 2054.50,
    "tax": 10.45
}

###
GET http://localhost:8000/orders HTTP/1.1
Host: localhost:8000
Content-Type: application/json