
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Marcos Doe",
    "email": "user@email.com",
    "password": "123456"
}

###
POST http://localhost:8000/users/generate_token
Content-Type: application/json

{
    "email": "user@email.com",
    "password": "123456"
}

###
