apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: wesleywillians/21-deploy-k8s:latest
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        
        # startup probe
        startupProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 10

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 2
          timeoutSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
          successThreshold: 1


        ports:
        - containerPort: 8080